# Generated by Django 5.2.11 on 2026-03-01 11:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0008_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensor',
            name='restroom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sensors', to='landing.restroom'),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='sensor_type',
            field=models.CharField(help_text='Type of sensor (e.g. Ammonia,Footfall)', max_length=50),
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('restroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='landing.restroom')),
                ('sensor_reading', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='landing.sensorreading')),
            ],
        ),
    ]
