# Generated by Django 5.2.11 on 2026-03-02 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0009_alter_sensor_restroom_alter_sensor_sensor_type_alert'),
    ]

    operations = [
        migrations.AddField(
            model_name='restroom',
            name='chat_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
