# Generated by Django 5.2.11 on 2026-03-03 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0010_restroom_chat_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='resolved',
            field=models.BooleanField(default=False),
        ),
    ]
