# Generated by Django 5.1.7 on 2026-03-25 20:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0011_alert_resolved'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(choices=[(1, '1 - Very Poor'), (2, '2 - Poor'), (3, '3 - Average'), (4, '4 - Good'), (5, '5 - Excellent')], help_text='Rating from 1 (Very Poor) to 5 (Excellent)')),
                ('comment', models.TextField(blank=True, help_text='Optional feedback comment', null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, help_text='Time when feedback was submitted')),
                ('restroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='landing.restroom')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
