# Generated by Django 5.2.11 on 2026-03-29 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0012_feedback'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sensor',
            name='threshold_min',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='nfc_tag',
        ),
        migrations.DeleteModel(
            name='CleaningActivity',
        ),
    ]
